mtk: perf_tracker: a function declaration without a prototype is deprecated
../kernel/drivers/misc/mediatek/perf/perf_tracker.c:190:43: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) get_cur_vcore_uv()
                                          ^
                                           void
../kernel/drivers/misc/mediatek/perf/perf_tracker.c:195:42: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) get_cur_ddr_khz()
                                         ^
                                          void
2 errors generated.

Signed-off-by: Rama Bondan Prakoso <ramanarubp@gmail.com>